### ISSUE TITLE
PLTL dependency prevents from running tests

### ISSUE THREAD

**Issue by MarkusRabe** [mvcisback/py-aiger#120]
https://github.com/mvcisback/py-aiger/blob/48aafe3e1ffe01caac42a12bfc6cf90a5c4229ff/aiger/hypothesis.py#L3

**Comment by mvcisback** [comment]
Hey Markus,

`aiger_ptltl` is listed as a development dependency.

https://github.com/mvcisback/py-aiger/blob/master/pyproject.toml#L30

**Comment by mvcisback** [comment]
Is this from trying to run when installing using pip?

**Comment by MarkusRabe** [comment]
Ah, I only searched for pltl ...

Thanks for the help!
