### ISSUE TITLE
Support for aig files

### ISSUE THREAD

**Issue by masinag** [mvcisback/py-aiger#129]
Hi,
I think it would be nice to support also parsing of _*.aig_ files ([binary format](https://github.com/arminbiere/aiger/blob/5f8ce5ca5fc42a06e5d713309f99195a740ac2b4/FORMAT#L407)).

If you'd like, I can start working on it and open a pull request.

**Comment by mvcisback** [comment]
Thanks! I look forward to it.

**Comment by mvcisback** [comment]
Released as version v6.2.0
