### ISSUE TITLE
Aiger Object API Update

### ISSUE THREAD

**Issue by mvcisback** [mvcisback/py-aiger#21]
Ideas:
1. Rename `top_level` to `cones` to indicate that it is the cones of influence.
2. Rename `cones` to `unnamed_cones`.

**Comment by MarkusRabe** [comment]
Maybe `entry_points` or `top_level_nodes`?

The cone (of influence) is typically the whole set of nodes on which the outputs depend. Since the cone of influence reduction is implicit in the data structure, I don't see the need to mention it in the naming scheme.
