### ISSUE TITLE
Boolean Expression output target

### ISSUE THREAD

**Issue by mvcisback** [mvcisback/py-aiger#32]
- [ ] boolean.py seems like a nice library to sit on top of.
- [ ] Might need to use Tseytin transformation to avoid encoding blow up.

**Comment by mvcisback** [comment]
@MarkusRabe please put any notes/thoughts regarding the CNF encoding in this thread.

**Comment by MarkusRabe** [comment]
Not sure why we should do that. That library does not seem to solve any of our problems.

**Comment by mvcisback** [comment]
@MarkusRabe, yeah this issue predates the discussion of a CNF output target or anything like that.

I more meant include your thoughts regarding what the necessary features of the encoding are.

**Comment by mvcisback** [comment]
Moved to py-aiger-analysis
