### ISSUE TITLE
aiger.tee({}) crashes

### ISSUE THREAD

**Issue by MarkusRabe** [mvcisback/py-aiger#33]
Snippet of a stack trace:

File "/Users/markus/work/py-aiger/aiger/common.py", line 122, in tee
    node_map=frozenset.union(*starmap(tee_output, outputs.items())),
TypeError: descriptor 'union' of 'frozenset' object needs an argument

Could this maybe return the empty circuit?

**Comment by mvcisback** [comment]
Good idea. Done. 78747c76b91f52e8d85c866e6ad85848e9dc5064
