### ISSUE TITLE
Handling of latches is unreasonably inefficient

### ISSUE THREAD

**Issue by MarkusRabe** [mvcisback/py-aiger#34]
aig.cutlatches() and aig.latches.items() appear to take forever for a file with around 15k gates and a couple of hundred latches. File [6s10_c0to7.aag](https://drive.google.com/open?id=18tV9r7Fqf99qFDcn5rTSfrDYZHXJ3WW7)

**Comment by mvcisback** [comment]
@MarkusRabe yeah, this is certainly a pain point of the current design. I need to traverse through the circuit to the latches and change them to inputs. This could be made slightly better using a hand optimized traversal compared to lens. That said I think a better solution is the following idea I've been playing with:

1. Remove the type of LatchIn. LatchIn and Inputs are only distinguished by a lookup table saying whether that input is or is not a latch.
2. Cut latches is now just a manipulation of said lookup table.

**Comment by MarkusRabe** [comment]
Sounds like a good design.

**Comment by mvcisback** [comment]
Fixed in #51
