### ISSUE TITLE
Crash upon cutting latches

### ISSUE THREAD

**Issue by MarkusRabe** [mvcisback/py-aiger#36]
The following piece of code crashes:

aig = parser.load('problem2.aag')
aig.cutlatches(aig.latches)

[problem2.txt](https://github.com/mvcisback/py-aiger/files/2237696/problem2.txt)

**Comment by mvcisback** [comment]
I believe this is due to some of the LatchIns never being used. See #37.

The proposed change to LatchIns #34 should address this bug.

**Comment by mvcisback** [comment]
Fixed in: 2b342218e8d22e55675ce0942f7f7c18aa34c3a7
